#!/bin/bash
#for test in 1 2a 2b 2c 2d 2e 2z 3a 3b 4 5a 5b 5c 5d 5e 6a 6b 6c; do
for test in 1 2a 2b 2c 2d 2e 2z 3a 3b 4 4b 5a 5b 5c 5e ; do
#for test in 1 2a 2b 2c 2d 2e 2z; do
    test/runt test$test
done

