#!/bin/bash
./pascal test/$1.pas pascalout.sl
RETVAL=$?
if [ $RETVAL -ne 0 ] 
then
  echo $1 FAILED to compile ------- && exit
#else
  #xmllint --format out.xml -o out2.xml
  #RETVAL=$?
  #[ $RETVAL -ne 0 ] && echo $1 FAILED ----- && exit
fi

#test/minc langout.c

slasm pascalout.sl io320.sl
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
  echo $1 FAILED to assemble ---------
  exit
fi

stackl pascalout > out

diff -qbwB out test/$1.correct
RETVAL=$?
[ $RETVAL -eq 0 ] && echo $1 PASSED
[ $RETVAL -ne 0 ] && diff -bwB out test/$1.correct && echo $1 FAILED to run ----
exit $RETVAL
