#pragma once
#include "cSymbol.h"
#include "cAstNode.h"
//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Phil Howard phil.howard@oit.edu
//

// parse function generated by bison
int yyparse();

// lexer function generated by flex
int yylex();

extern char *yytext;        // text of the current token
extern int yylineno;        // line number of current token
extern FILE *yyin;          // input file for lexer
extern cAstNode *yyast_root;
/*
typedef struct
{
    cSymbol *symbol;
} yylval_t;

extern yylval_t yylval;*/
